name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 22 * * 1,2,3,4,5

jobs:
  test-cafe-checkout:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: thomasgoldberger/testcafe
        path: main
  
  test-cafe-run:
    uses: thomasgoldberger/testcafe/.github/workflows/main.yaml@main
    
  # playwright-test:
  #   uses:
  #     DigitalRetailing/dr-ui-automation-test/.github/workflows/smoke.yml@US1015087_DDC