name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 22 * * 1,2,3,4,5

jobs:
  # test-cafe-run:
  #   name: Run end-to-end test with test_e2e_testcafe
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-node@v3
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: thomasgoldberger/testcafe
  #         path: main

  #     - name: Install testcafe dependencies
  #       run: npm install -g testcafe
  #       working-directory: main

  #     - name: Run tests headless
  #       run:  testcafe "chrome:headless" ./examples/basic/test.js
  #       working-directory: main
  test-cafe-run:
    uses: thomasgoldberger/testcafe/.github/workflows/main.yaml@main

  # playwright-test:
  #   uses:
  #     DigitalRetailing/dr-ui-automation-test/.github/workflows/smoke.yml@US1015087_DDC